### ISSUE TITLE
Enter engages mic again

### ISSUE THREAD

**Issue by shinningweb** [Daniel-Hug/speech-input#6]
when using a single input field, enter engages the mic again. Click should engage mic, enter should submit form

**Comment by shinningweb** [comment]
i have found a solution, this will cause the form to be submitted when enter key is pressed

` <script>
    document.getElementById('command').addEventListener('keypress', function(event) {
        if (event.keyCode == 13) {
            document.forms[0].submit();
        }
    });
</script>`

**Comment by Daniel-Hug** [comment]
This looks like a bug. I will look more at this soon, Lord willing. Thanks for the help! :)

**Comment by Daniel-Hug** [comment]
Found a fix. Thanks again.
